### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by dimmduh** [needle-tools/compilation-visualizer#5] opened 2021-01-21 18:30 UTC
but added com.needle.compilation-visualizer to scopes in settings.
And now it shows in package manager and works

**Comment by hybridherbst** [comment] 2021-01-21 19:04
Hi, not sure what the issue is here - which part of the installation did not work?

**Comment by dimmduh** [comment] 2021-01-22 07:09
last step - unity shows error - can not find repo
![image](https://user-images.githubusercontent.com/446814/105458546-c3e6e800-5cc3-11eb-92bb-02b203f9c9df.png)
unity 2020.2

**Comment by hybridherbst** [comment] 2021-01-22 09:22
Ah, my bad! Was a copy-paste error, the line with "Scope(s)" should read `com.needle.compilation-visualizer` as well.

Fixed in https://github.com/needle-tools/compilation-visualizer/commit/9321c1c90f3fd666d76acd7cd72769f98b78fb23

**Closed as completed by hybridherbst** 2021-01-22 09:22 UTC
